---
namespace: trippsc2
name: windows
version: 1.1.3
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains general purpose Windows modules and roles.

license_file: 'LICENSE'

tags:
  - infrastructure
  - windows

dependencies:
  ansible.utils: '>=2.5.0'
  ansible.windows: '>=1.5.0'
  community.windows: '>=1.5.0'

repository: https://github.com/trippsoft/ansible-collection-windows.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
