---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: deployment_services
  description: This role installs and configures Windows Deployment Services role on Windows Server.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Windows
      versions:
        - '2025'
        - '2022'
        - '2019'

collections:
  - ansible.windows
  - community.windows

dependencies: []
