---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: win
    box: jtarpley/${MOLECULE_BOX:-w2025_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: windows_testing_chocolatey_
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      subjects:
        choco_configure_testing_repo: ${MOLECULE_CONFIGURE_TESTING_REPO:-true}
        choco_testing_repo_name: Testing
        choco_testing_repo_url: ${MOLECULE_TESTING_REPO_URL:-http://192.168.81.5:8081/repository/chocolatey-proxy/}
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
        ansible_password: vagrant
    host_vars:
      win:
        ansible_ssh_common_args: >-
          -o PreferredAuthentications=password
          -o PubkeyAuthentication=no
          -o UserKnownHostsFile=/dev/null
          -o ControlMaster=auto
          -o ControlPersist=60s
          -o ForwardX11=no
          -o LogLevel=ERROR
          -o StrictHostKeyChecking=no
verifier:
  name: ansible
