---
name: Generate Role Docs
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/deployment_services/.aar_doc.yml
      - roles/deployment_services/README.md
      - roles/deployment_services/meta/argument_specs.yml
      - roles/deployment_services/meta/main.yml
      - roles/dhcp_server/.aar_doc.yml
      - roles/dhcp_server/README.md
      - roles/dhcp_server/meta/argument_specs.yml
      - roles/dhcp_server/meta/main.yml
      - roles/install_psgallery/.aar_doc.yml
      - roles/install_psgallery/README.md
      - roles/install_psgallery/meta/argument_specs.yml
      - roles/install_psgallery/meta/main.yml
      - roles/testing_chocolatey/.aar_doc.yml
      - roles/testing_chocolatey/README.md
      - roles/testing_chocolatey/meta/argument_specs.yml
      - roles/testing_chocolatey/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.windows'
jobs:
  docs_deployment_services:
    name: Generate deployment_services role documentation
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.windows
          ref: main
      - name: Generate deployment_services role documentation
        working-directory: 'trippsc2.windows'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/deployment_services
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update deployment_services role documentation." || /bin/true
          git push origin main
          deactivate
  docs_dhcp_server:
    name: Generate dhcp_server role documentation
    needs: docs_deployment_services
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.windows
          ref: main
      - name: Generate dhcp_server role documentation
        working-directory: 'trippsc2.windows'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/dhcp_server
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update dhcp_server role documentation." || /bin/true
          git push origin main
          deactivate
  docs_install_psgallery:
    name: Generate install_psgallery role documentation
    needs: docs_dhcp_server
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.windows
          ref: main
      - name: Generate install_psgallery role documentation
        working-directory: 'trippsc2.windows'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/install_psgallery
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update install_psgallery role documentation." || /bin/true
          git push origin main
          deactivate
  docs_testing_chocolatey:
    name: Generate testing_chocolatey role documentation
    needs: docs_install_psgallery
    permissions:
      contents: write
    runs-on:
      - self-hosted
      - linux
      - ansible
      - x64
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: trippsc2.windows
          ref: main
      - name: Generate testing_chocolatey role documentation
        working-directory: 'trippsc2.windows'
        run: |
          source ~/venv/ansible-2.16/bin/activate
          cd ./roles/testing_chocolatey
          aar-doc . markdown
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git add README.md || /bin/true
          git commit -m "Update testing_chocolatey role documentation." || /bin/true
          git push origin main
          deactivate
