---
name: Molecule - dhcp_server role
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/dhcp_server/**
      - '!roles/dhcp_server/.aar_doc.yml'
      - '!roles/dhcp_server/README.md'
      - '!roles/dhcp_server/meta/argument_specs.yml'
      - '!roles/dhcp_server/meta/main.yml'
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - roles/dhcp_server/**
      - '!roles/dhcp_server/.aar_doc.yml'
      - '!roles/dhcp_server/README.md'
      - '!roles/dhcp_server/meta/argument_specs.yml'
      - '!roles/dhcp_server/meta/main.yml'
defaults:
  run:
    working-directory: 'trippsc2.windows'
jobs:
  molecule:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.windows'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          cd ./roles/dhcp_server
          molecule test
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
