---
name: Molecule - wds_boot_image module plugin
'on':
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/module_utils/WDS.psm1
      - plugins/modules/wds_boot_image.ps1
  push:
    branches:
      - main
    paths:
      - galaxy.yml
      - plugins/module_utils/WDS.psm1
      - plugins/modules/wds_boot_image.ps1
defaults:
  run:
    working-directory: 'trippsc2.windows'
jobs:
  molecule:
    name: Run Molecule tests
    runs-on:
      - self-hosted
      - linux
      - x64
    strategy:
      fail-fast: false
      matrix:
        box:
          - w2025_cis
          - w2022_cis
          - w2019_cis
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'trippsc2.windows'
      - name: Run Molecule tests
        run: |
          source ~/venv/ansible-2.16/bin/activate
          rm -rf ~/.ansible/collections/ansible_collections/*
          molecule test -s wds_boot_image
          rm -rf ~/.ansible/collections/ansible_collections/*
          deactivate
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          MOLECULE_BOX: ${{ matrix.box }}
